### ISSUE TITLE
Support config option to not post coverage

### ISSUE THREAD

**Issue by probablyup** [mattallty/jest-github-action#10]
In our project we don't care about coverage too much so I'd love the ability to specify not to post the coverage comment.

**Comment by davidhousedev** [comment]
Looks like this is supported: https://github.com/mattallty/jest-github-action/blob/40eafe1b6e3924992dd7e3b0a07e70dfdff1d52f/src/action.ts#L80

Perhaps some documentation might help, perhaps another example along the lines of:

```yaml
uses: mattallty/jest-github-action@v1
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
with:
  # include this boolean to avoid reporting code coverage
  coverage-comment: false
```

I haven't tested it myself, though.
