### ISSUE TITLE
Error on launching test

### ISSUE THREAD

**Issue by Ciloe** [mattallty/jest-github-action#30]
Hi there, 

I would like to use your container. But I have an error : 

```
Run mattallty/jest-github-action@v1.0.3
  with:
    working-directory: react
    test-command: yarn run test
    coverage-comment: true
    changes-only: false
  env:
    GITHUB_TOKEN: ***
Jest execution failed. Tests have likely failed. Error: The process '/usr/bin/yarn' failed with exit code 127
Error: ENOENT: no such file or directory, open '/home/runner/work/directory/project/react/jest.results.json'
    at ExecState._setResult (/home/runner/work/_actions/mattallty/jest-github-action/v1.0.3/dist/index.js:1:15037)
    at ExecState.CheckComplete (/home/runner/work/_actions/mattallty/jest-github-action/v1.0.3/dist/index.js:1:14599)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/mattallty/jest-github-action/v1.0.3/dist/index.js:1:13563)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Error: ENOENT: no such file or directory, open '/home/runner/work/directory/project/react/jest.results.json'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at parseResults (/home/runner/work/_actions/mattallty/jest-github-action/v1.0.3/dist/index.js:1:24599)
    at Object.<anonymous> (/home/runner/work/_actions/mattallty/jest-github-action/v1.0.3/dist/index.js:1:21871)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/mattallty/jest-github-action/v1.0.3/dist/index.js:1:20705)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/runner/work/directory/project/react/jest.results.json'
}
```

This is my configuration file

```yaml
  jest:
    name: Jest
    runs-on: ubuntu-latest
    needs: [ eslint, csslint, tslint ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Jest Annotations & Coverage
        uses: mattallty/jest-github-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working-directory: "react"
          test-command: "yarn run test"
```

Any ideas ?
